# Generated by Django 3.1.4 on 2021-01-07 20:33

from django.conf import settings
import django.contrib.gis.db.models.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogColour',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('hex', models.CharField(default='#000000', max_length=7, validators=[django.core.validators.RegexValidator('^#[A-F0-9]{6}$', flags=re.RegexFlag['IGNORECASE'], message='Enter a valid hexfigure: e.g. "ff0022"')])),
                ('name', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'db_table': 'catalog_colour',
            },
        ),
        migrations.CreateModel(
            name='HistoricalCountry',
            fields=[
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('code', models.CharField(db_index=True, max_length=5)),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('name_iso_country', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('code_iso3_country', models.CharField(blank=True, db_index=True, max_length=3, null=True)),
                ('wikidata', models.JSONField(blank=True, null=True)),
                ('pop_est', models.IntegerField(blank=True, null=True)),
                ('gdp_md_est', models.IntegerField(blank=True, null=True)),
                ('economy', models.CharField(blank=True, max_length=100, null=True)),
                ('income_grp', models.CharField(blank=True, max_length=100, null=True)),
                ('continent', models.CharField(blank=True, max_length=100, null=True)),
                ('region_un', models.CharField(blank=True, max_length=100, null=True)),
                ('subregion', models.CharField(blank=True, max_length=100, null=True)),
                ('region_wb', models.CharField(blank=True, max_length=100, null=True)),
                ('border', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
                ('bbox', django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('colour', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sample_app.catalogcolour')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical country',
                'db_table': 'historic_countries',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=5, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('name_iso_country', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('code_iso3_country', models.CharField(blank=True, max_length=3, null=True, unique=True)),
                ('wikidata', models.JSONField(blank=True, null=True)),
                ('pop_est', models.IntegerField(blank=True, null=True)),
                ('gdp_md_est', models.IntegerField(blank=True, null=True)),
                ('economy', models.CharField(blank=True, max_length=100, null=True)),
                ('income_grp', models.CharField(blank=True, max_length=100, null=True)),
                ('continent', models.CharField(blank=True, max_length=100, null=True)),
                ('region_un', models.CharField(blank=True, max_length=100, null=True)),
                ('subregion', models.CharField(blank=True, max_length=100, null=True)),
                ('region_wb', models.CharField(blank=True, max_length=100, null=True)),
                ('border', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
                ('bbox', django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326)),
                ('colour', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sample_app.catalogcolour')),
            ],
            options={
                'verbose_name_plural': 'Countries',
                'db_table': 'country',
            },
        ),
    ]
