# Generated by Django 3.1.5 on 2021-01-11 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample_app', '0002_load_countries'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='wikipedia',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalcountry',
            name='wikipedia',
            field=models.TextField(blank=True, null=True),
        ),
    ]
